version: '3.7'

services:
  recorder:
    build:
      context: .
      dockerfile: Dockerfile-recorder
    volumes:
      - video:/app/media

  packager:
    image: google/shaka-packager
    command:
      - /bin/sh
      - -c
      - |
        packager 'in=udp://0.0.0.0:40001?reuse=1,stream=video,segment_template=/video/live_288p/$$Number$$.ts,playlist_name=/video/live_288p/main.m3u8,iframe_playlist_name=/video/live_288p/iframe.m3u8' \
        'in=udp://0.0.0.0:40002?reuse=1,stream=video,segment_template=/video/live_432p/$$Number$$.ts,playlist_name=/video/live_432p/main.m3u8,iframe_playlist_name=/video/live_432p/iframe.m3u8' \
        --hls_master_playlist_output /video/live.m3u8 \
        --hls_playlist_type LIVE
    volumes:
      - video:/video
    ports:
      - "40001:40001/udp"
      - "40002:40002/udp"

  minio1:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  video: